name: oyimg
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip
  - scipy
  - tifffile
  - tqdm
  - opencv
  - jupyter
  - matplotlib
  - pandas
  - scikit-image
  - scikit-learn
  - numba
  - dill
  - cmake
  - nd2reader
  - napari
  - pyfftw
  - pip:
    - cellpose
    - lap

